version: '3.8'
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: poker
      POSTGRES_PASSWORD: password
      POSTGRES_DB: poker_trainer
    ports:
      - "5435:5432"
      - db-data:/var/lib/postgresql/data

#  backend:
#    build:
#      context: ./server
#      dockerfile: Dockerfile.server
#    restart: always
#    ports:
#      - "3001:3001"
#    environment:
#      DATABASE_URL: postgres://poker:password@db:5432/poker_trainer
#    depends_on:
#      - db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
#    depends_on:
#      - backend

volumes:
  db-data:
